/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimsIndexRouteImport } from './routes/claims.index'
import { Route as ClaimsNewRouteImport } from './routes/claims.new'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims.$claimId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsNewRoute = ClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims/': typeof ClaimsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims': typeof ClaimsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims/': typeof ClaimsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/payments'
    | '/profile'
    | '/support'
    | '/claims/$claimId'
    | '/claims/new'
    | '/claims/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/payments'
    | '/profile'
    | '/support'
    | '/claims/$claimId'
    | '/claims/new'
    | '/claims'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/login'
    | '/payments'
    | '/profile'
    | '/support'
    | '/claims/$claimId'
    | '/claims/new'
    | '/claims/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SupportRoute: typeof SupportRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  ClaimsNewRoute: typeof ClaimsNewRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/new': {
      id: '/claims/new'
      path: '/claims/new'
      fullPath: '/claims/new'
      preLoaderRoute: typeof ClaimsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SupportRoute: SupportRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  ClaimsNewRoute: ClaimsNewRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
